apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ondat-encryption-replication-topology-aware-placement
provisioner: csi.storageos.com
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: "ext4"
  csi.storage.k8s.io/secret-name: "storageos-api"
  csi.storage.k8s.io/secret-namespace: "storageos"
  storageos.com/encryption: "true"                 # encrypts the contents of the volume.
  storageos.com/replicas: "2"                      # number of replicated volumes across nodes.
  storageos.com/topology-aware: "true"             # enable topology-aware placement.
  storageos.com/failure-mode: "soft"               # set volume failure mode to soft.